Update android-wait-for-emulator for Lollipop
Either adb output changed, or there is a component in Android SDK
that now writes "device offline" instead of "device not found".

Whatever the case, we need to check for this additional output
so that we can get out of the loop.

Additionally, we explicitly wait for the output "running", in order
to get out of the loop.

Finally, the components may need a little longer than 15 seconds
to be ready, so we raise the timeout to 60 seconds.

diff --git a/ci_environment/android-sdk/files/default/android-wait-for-emulator b/ci_environment/android-sdk/files/default/android-wait-for-emulator
--- a/ci_environment/android-sdk/files/default/android-wait-for-emulator
+++ b/ci_environment/android-sdk/files/default/android-wait-for-emulator
@@ -6,16 +6,20 @@ set +e
 
 bootanim=""
 failcounter=0
+timeout_in_sec=60
+
 until [[ "$bootanim" =~ "stopped" ]]; do
-   bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
-   echo "$bootanim"
-   if [[ "$bootanim" =~ "not found" ]]; then
-      let "failcounter += 1"
-      if [[ $failcounter -gt 15 ]]; then
-        echo "Failed to start emulator"
-        exit 1
-      fi
-   fi
-   sleep 1
+  bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
+  if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline" ]]; then
+    let "failcounter += 1"
+    echo "Waiting for emulator to start"
+    if [[ $failcounter -gt timeout_in_sec ]]; then
+      echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
+      exit 1
+    fi
+  elif [[ "$bootanim" =~ "running" ]]; then
+    echo "Emulator is ready"
+    exit 0
+  fi
+  sleep 1
 done
-echo "Done"
