Echo error to >&2

diff --git a/ci_environment/haskell/templates/default/ghc_finder.sh.erb b/ci_environment/haskell/templates/default/ghc_finder.sh.erb
--- a/ci_environment/haskell/templates/default/ghc_finder.sh.erb
+++ b/ci_environment/haskell/templates/default/ghc_finder.sh.erb
@@ -8,6 +8,6 @@ function ghc_find() {
         break
       fi
     done
-    echo "ghc_find: error, no such version $1"
+    echo "ghc_find: error, no such version $1" >&2
   fi
 }
