Trim down the travis_kerl cookbook
to only manage binary installations

diff --git a/cookbooks/travis_kerl/files/default/build_plt b/cookbooks/travis_kerl/files/default/build_plt
--- a/cookbooks/travis_kerl/files/default/build_plt
+++ b/cookbooks/travis_kerl/files/default/build_plt
@@ -2,14 +2,17 @@
 
 . "$1/activate"
 
+APPS=$(ls "$2" | sed 's/-.*//' | grep -v jinterface | grep -v erl_interface)
+
 dialyzer --output_plt "${REBAR_PLT_DIR}/dialyzer.plt" \
          --build_plt \
-         --apps `ls "$2" | sed 's/-.*//' | grep -v jinterface | grep -v erl_interface`
+         --apps ${APPS}
+
 status=$?
-if [ $status -eq 2 ]; then
-    # dialyzer(3): exit status 2 - No problems were encountered,
-    # but warnings were emitted.
-    exit 0
+if [ $status -eq 2 ] ; then
+  # dialyzer(3): exit status 2 - No problems were encountered,
+  # but warnings were emitted.
+  exit 0
 else
-    exit $status
+  exit $status
 fi
