Import mongodb version 0.16.2

diff --git a/community-cookbooks/mongodb/templates/default/debian-mongodb.init.erb b/community-cookbooks/mongodb/templates/default/debian-mongodb.init.erb
--- a/community-cookbooks/mongodb/templates/default/debian-mongodb.init.erb
+++ b/community-cookbooks/mongodb/templates/default/debian-mongodb.init.erb
@@ -3,6 +3,8 @@
 # init.d script with LSB support.
 #
 # Copyright (c) 2007 Javier Fernandez-Sanguino <jfs@debian.org>
+# Copyright (c) 2011 edelight GmbH
+#       Author: Markus Korn <markus.korn@edelight.de>
 #
 # This is free software; you may redistribute it and/or modify
 # it under the terms of the GNU General Public License as
@@ -20,49 +22,63 @@
 # Suite 330, Boston, MA 02111-1307 USA
 #
 ### BEGIN INIT INFO
-# Provides:          mongodb
+# Provides:          <%= @provides %>
 # Required-Start:    $network $local_fs $remote_fs
 # Required-Stop:     $network $local_fs $remote_fs
 # Should-Start:      $named
 # Should-Stop:
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: An object/document-oriented database
-# Description:       MongoDB is a high-performance, open source, schema-free 
+# Short-Description: Start/stop <%= @provides %> An object/document-origented database
+# Description:       MongoDB is a high-performance, open source, schema-free
 #                    document-oriented  data store that's easy to deploy, manage
 #                    and use. It's network accessible, written in C++ and offers
 #                    the following features:
-#                    
+#
 #                       * Collection oriented storage - easy storage of object-
 #                         style data
 #                       * Full index support, including on inner objects
 #                       * Query profiling
 #                       * Replication and fail-over support
-#                       * Efficient storage of binary data including large 
+#                       * Efficient storage of binary data including large
 #                         objects (e.g. videos)
 #                       * Auto-sharding for cloud-level scalability (Q209)
-#                    
+#
 #                    High performance, scalability, and reasonable depth of
 #                    functionality are the goals for the project.
 ### END INIT INFO
+#
+NAME=<%= @provides %>
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/usr/bin/mongod
 DESC=database
-
-# Default defaults.  Can be overridden by the /etc/default/$NAME
-NAME=mongodb
-CONF=/etc/mongodb.conf
-DATA=/var/lib/mongodb
-LOGDIR=/var/log/mongodb
 PIDFILE=/var/run/$NAME.pid
-LOGFILE=$LOGDIR/$NAME.log  # Server logfile
 ENABLE_MONGODB=yes
-LOCKFILE=${DATA}/mongod.lock
+SYSCONFIG=<%= @sysconfig_file %>
+
+# this should get removed at some point for more shell agnostic init script
+ulimit -f <%= @ulimit['fsize'] %>
+ulimit -t <%= @ulimit['cpu'] %>
+ulimit -v <%= @ulimit['as'] %>
+ulimit -n <%= @ulimit['nofile'] %>
+ulimit -m <%= @ulimit['rss'] %>
+ulimit -u <%= @ulimit['nproc'] %>
 
 # Include mongodb defaults if available
-if [ -f /etc/default/$NAME ] ; then
-        . /etc/default/$NAME
+if [ -f $SYSCONFIG ] ; then
+    . $SYSCONFIG
+fi
+
+# Handle NUMA access to CPUs (SERVER-3574)
+# This verifies the existence of numactl as well as testing that the command works
+NUMACTL_ARGS="--interleave=all"
+if which numactl >/dev/null 2>/dev/null && numactl $NUMACTL_ARGS ls / >/dev/null 2>/dev/null
+then
+    NUMACTL="`which numactl` -- $NUMACTL_ARGS"
+    DAEMON_OPTS="$DAEMON_OPTS"
+else
+    NUMACTL=""
+    DAEMON_OPTS="-- $DAEMON_OPTS"
 fi
 
 if test ! -x $DAEMON; then
@@ -74,21 +90,18 @@ if test "x$ENABLE_MONGODB" != "xyes"; then
     exit 0
 fi
 
-if test ! -x $DATA; then
-    mkdir $DATA || exit 0
-fi
-
 . /lib/lsb/init-functions
 
 STARTTIME=1
-DIETIME=10                   # Time to wait for the server to die, in seconds
+DIETIME=10                  # Time to wait for the server to die, in seconds
                             # If this value is set too low you might not
                             # let some servers to die gracefully and
                             # 'restart' will not work
 
-DAEMONUSER=${DAEMONUSER:-mongodb}
-DAEMON_OPTS=${DAEMON_OPTS:-"--dbpath $DATA --logpath $LOGFILE run"}
-DAEMON_OPTS="$DAEMON_OPTS --config $CONF"
+DAEMON_USER=${DAEMON_USER:-mongodb}
+
+# debugging
+echo "** Running $NAME ($DAEMON $DAEMON_OPTS)"
 
 set -e
 
@@ -113,78 +126,67 @@ running() {
     [ ! -f "$PIDFILE" ] && return 1
     pid=`cat $PIDFILE`
     running_pid $pid $DAEMON || return 1
-    return 0
+    for i in `seq 1 20`; do
+      nc -z <%= @bind_ip %> <%= @port %> && return 0
+      echo -n "."
+      sleep 15
+    done
+    return 1
 }
 
 start_server() {
 # Start the process using the wrapper
             start-stop-daemon --background --start --quiet --pidfile $PIDFILE \
-                        --make-pidfile --chuid $DAEMONUSER \
-                        --exec $DAEMON -- $DAEMON_OPTS
+                        --make-pidfile --chuid $DAEMON_USER \
+                        --exec $NUMACTL $DAEMON $DAEMON_OPTS
             errcode=$?
-        return $errcode
+    return $errcode
 }
 
 stop_server() {
 # Stop the process using the wrapper
             start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                         --retry 300 \
-                        --user $DAEMONUSER \
+                        --user $DAEMON_USER \
                         --exec $DAEMON
             errcode=$?
-        return $errcode
+    return $errcode
 }
 
 force_stop() {
 # Force the process to die killing it manually
-        [ ! -e "$PIDFILE" ] && return
+    [ ! -e "$PIDFILE" ] && return
+    if running ; then
+        kill -15 $pid
+    # Is it really dead?
+        sleep "$DIETIME"s
         if running ; then
-                kill -15 $pid
-        # Is it really dead?
-                sleep "$DIETIME"s
-                if running ; then
-                        kill -9 $pid
-                        sleep "$DIETIME"s
-                        if running ; then
-                                echo "Cannot kill $NAME (pid=$pid)!"
-                                exit 1
-                        fi
-                fi
+            kill -9 $pid
+            sleep "$DIETIME"s
+            if running ; then
+                echo "Cannot kill $NAME (pid=$pid)!"
+                exit 1
+            fi
         fi
-        rm -f $PIDFILE
+    fi
+    rm -f $PIDFILE
 }
 
-system_starting() {
-        if [[ $PREVRUNLEVEL -eq 0 ]] || [[ $PREVRUNLEVEL -eq 6 ]]; then
-                return 1
-        else
-                return 0
-        fi
-}
-
-break_mongod_lock() {
-        rm -f ${LOCKFILE}
-}
 
 case "$1" in
   start)
-        log_daemon_msg "Starting $DESC" "$NAME"
+    log_daemon_msg "Starting $DESC" "$NAME"
         # Check if it's running first
         if running ;  then
             log_progress_msg "apparently already running"
             log_end_msg 0
             exit 0
         fi
-        
-        if system_starting ; then
-            break_mongod_lock
-        fi
-        
         if start_server ; then
             # NOTE: Some servers might die some time after they start,
             # this code will detect this issue if STARTTIME is set
             # to a reasonable value
-            [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time 
+            [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time
             if  running ;  then
                 # It's ok, the server started and is running
                 log_end_msg 0
@@ -196,12 +198,12 @@ case "$1" in
             # Either we could not start it
             log_end_msg 1
         fi
-        ;;
+    ;;
   stop)
         log_daemon_msg "Stopping $DESC" "$NAME"
         if running ; then
             # Only stop the server if we see it running
-                        errcode=0
+            errcode=0
             stop_server || errcode=$?
             log_end_msg $errcode
         else
@@ -217,14 +219,14 @@ case "$1" in
         if running; then
             # If it's still running try to kill it more forcefully
             log_daemon_msg "Stopping (force) $DESC" "$NAME"
-                        errcode=0
+            errcode=0
             force_stop || errcode=$?
             log_end_msg $errcode
         fi
-        ;;
+    ;;
   restart|force-reload)
         log_daemon_msg "Restarting $DESC" "$NAME"
-                errcode=0
+        errcode=0
         stop_server || errcode=$?
         # Wait some sensible amount, some server need this
         [ -n "$DIETIME" ] && sleep $DIETIME
@@ -232,7 +234,7 @@ case "$1" in
         [ -n "$STARTTIME" ] && sleep $STARTTIME
         running || errcode=$?
         log_end_msg $errcode
-        ;;
+    ;;
   status)
 
         log_daemon_msg "Checking status of $DESC" "$NAME"
@@ -252,10 +254,11 @@ case "$1" in
         ;;
 
   *)
-        N=/etc/init.d/$NAME
-        echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
-        exit 1
-        ;;
+    N=/etc/init.d/$NAME
+    echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
+    exit 1
+    ;;
 esac
 
 exit 0
+
